export const config = {
    readonly: false,
    // autofocus: false,
    enter: 'br',
    zIndex: 0,
    activeButtonsInReadOnly: ['source', 'fullsize', 'print', 'about'],
    toolbarButtonSize: 'middle',
    theme: 'default',
    enableDragAndDropFileToEditor: true,
    saveModeInCookie: false,
    spellcheck: true,
    editorCssClass: false,
    triggerChangeEvent: true,
    height: 220,
    direction: 'ltr',
    language: 'vi',
    debugLanguage: true,
    tabIndex: -1,
    toolbar: true,
    useSplitMode: false,
    colorPickerDefaultTab: 'background',
    imageDefaultWidth: 100,
    removeButtons: [
        'source',
        'fullsize',
        'about',
        'outdent',
        'indent',
        'video',
        'print',
        'table',
        'fontsize',
        'superscript',
        'subscript',
        'Insert link',
        'file',
        'cut',
        'selectall',
    ],
    disablePlugins: ['paste', 'stat'],
    events: {},
    textIcons: false,
    uploader: {
        insertImageAsBase64URI: true,
    },
    placeholder: '',
    showXPathInStatusbar: false,
}